spring:
  application:
    name: ILKAN-was
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  openai:
    api:
      key: ${OPENAI_API_KEY}



app:
  s3:
    bucket: ilkan-image
    region: ap-northeast-2
  cdn-base-url: "https://ilkan-image.s3.ap-northeast-2.amazonaws.com"


